name: CordCloud

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: yanglbme/cordcloud-action@main
        with:
          email: ${{ secrets.CC_EMAIL }}
          passwd: ${{ secrets.CC_PASSWD }}
          host: "www.cordc.co,www.cordc.xyz,www.cordc.cc,www.cordcloud.cloud,www.cordc.net"
